version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/index
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"